const fs = require('fs');
let data = fs.readFileSync('js/data.js', 'utf8');

const plots = {
  "Pather Panchali (Song of the Little Road)": "A poignant coming-of-age story of a young boy, Apu, and his family struggling with extreme poverty in a rural Bengali village.",
  "Aparajito (The Unvanquished)": "The second part of the Apu Trilogy, following Apu's journey from his village to study in Kolkata, creating a rift with his mother.",
  "The Music Room (Jalsaghar)": "A fading aristocratic landlord in rural Bengal desperately tries to hold onto his past wealth and prestige through lavish musical concerts.",
  "The World of Apu (Apur Sansar)": "The final chapter of the Apu trilogy, exploring adult Apu's struggles with unemployment, an unexpected marriage, and eventual fatherhood.",
  "Charulata (The Lonely Wife)": "A lonely, intellectual wife in 19th-century Bengal forms a deep emotional and creative bond with her husband's visiting cousin.",
  "The Cloud-Capped Star (Meghe Dhaka Tara)": "The tragic tale of Nita, a young woman in post-partition Bengal who sacrifices her own happiness and life to support her ungrateful refugee family.",
  "E-Flat (Komal Gandhar)": "A fragmented theatre troupe struggles with internal conflicts and the overarching trauma of the Bengal partition.",
  "Subarnarekha": "A haunting story of a brother and his adopted sister, whose lives are repeatedly torn apart by caste, class, and the tragedy of displacement after the partition.",
  "A River Called Titas (Titash Ekti Nadir Naam)": "A multi-narrative saga depicting the vibrant life, gradual decay, and tragic destruction of a fishing community on the banks of the Titas river.",
  "Reason, Debate and a Story (Jukti Takko Aar Gappo)": "An alcoholic intellectual, his estranged wife, and a group of marginalized youths wander through Bengal discussing philosophy, politics, and despair.",
  "Chorus": "An allegorical critique of capitalist exploitation, portraying striking workers, rural revolutionaries, and a fantastical corporate board.",
  "And Quiet Flows the Dawn (Ekdin Pratidin)": "A middle-class family faces severe moral panic and societal judgment when their primary breadwinner, a young unmarried daughter, fails to return home one night.",
  "In Search of Famine (Akaler Shandhane)": "A modern film crew arrives in a village to make a movie about the 1943 Bengal famine, only to trigger the unresolved trauma of the locals.",
  "The Case Is Closed (Kharij)": "A middle-class family's comfortable existence is shaken when their underage servant boy dies from carbon monoxide poisoning, revealing their profound apathy.",
  "Mr. and Mrs. Iyer": "A devout Hindu woman and a Muslim man must pose as a married couple to survive a horrific outbreak of communal violence during a bus journey.",
  "15 Park Avenue": "An exploration of schizophrenia through the eyes of a woman who believes she has a family living at a non-existent address, cared for by her older sister.",
  "The Japanese Wife": "A shy Bengali village schoolteacher conducts a long-distance, unconsummated marriage through letters with a Japanese woman for over a decade.",
  "Goynar Baksho (The Jewelry Box)": "A dark comedy spanning three generations of women and their relationship to a cursed box of ancestral jewelry, haunted by a fiercely possessive ghost.",
  "36 Chowringhee Lane": "An aging, lonely Anglo-Indian teacher in Kolkata finds temporary joy when she befriends a young Bengali couple, only to be ultimately used and discarded.",
  "Chokher Bali (A Passion Play)": "Based on Tagore's novel, a young, educated, and rebellious widow disrupts the lives of her friend and a young married couple when she moves into their household.",
  "Raincoat": "Two former lovers, now leading separate, desperate lives, reunite on a rainy afternoon in Kolkata and weave elaborate lies to hide their respective misery.",
  "The Last Lear": "An aging, eccentric Shakespearean actor finally agrees to perform in a modern cinematic film, leading to clashes with the director and tragic consequences.",
  "Abohomaan (The Eternal)": "A celebrated director forms an intense, scandalous emotional bond with an actress who strongly resembles his wife from their youth.",
  "The Shelter of the Wings (Charachar)": "A bird catcher feels profound empathy for his prey, choosing to set them free despite his family's resulting descent into poverty.",
  "The Wrestlers (Uttara)": "Two obsessively competitive wrestlers ignore the increasing presence of violent religious extremism in their village and the abuse of a young woman they both covet.",
  "A Tale of a Naughty Girl (Manda Meyer Upakhyan)": "A young girl in a brothel desperately attempts to escape her predetermined fate through education and an obsession with the moon landing.",
  "Tope (The Bait)": "A surreal exploration of exploitation where a wealthy aristocrat, a tightrope walker, and a documentary filmmaker cross paths in a rural village.",
  "Chotoder Chobi (A Short Story)": "A deeply humanistic love story between two individuals born with dwarfism, highlighting their daily struggles against societal apathy and mockery.",
  "Cinemawala": "An aging proprietor of a declining single-screen cinema hall faces ruin due to digital piracy, secretly orchestrated by his own son.",
  "Nagarkirtan": "A poignant and heartbreaking love story between a flute player and a transgender woman, navigating the brutal realities of marginalization in Kolkata.",
  "Jyeshthoputro (The Elder Son)": "A famous superstar returns to his ancestral village following his father's death, clashing with his resentful younger brother who stayed behind to manage the family.",
  "Shabdo: The Silence of the World": "A Foley artist becomes so obsessed with background sounds and ambient noise that he begins losing his grip on human speech and reality.",
  "22 Shey Srabon": "A suspended, eccentric police officer is brought back to help catch a serial killer who murders people based on the poetry of Bengali literature.",
  "Jaatishwar": "A Portuguese-origin man believes he is the reincarnation of Hensman Anthony, a famous 19th-century Bengali folk poet, blending two distinct timelines.",
  "Chotushkone": "Four rival film directors reunite to create an anthology film about death, leading to a suspenseful journey filled with hidden agendas and past grudges.",
  "Rajkahini (Tales of Queens)": "During the 1947 partition, a fierce brothel madam and her prostitutes violently defend their home when the new India-Pakistan border is drawn straight through it.",
  "Elippathayam": "A decaying, feudal patriarchal landlord in Kerala is unable to adapt to changing social realities, gradually descending into severe paranoia and isolation.",
  "Anantaram": "A complex psychological exploration of a young man's fragmented memory and inner struggles, presented through a non-linear, introspective narrative.",
  "Mathilukal": "Based on a true story, an imprisoned writer falls deeply in love with a female inmate he can only hear but never see across a high prison wall.",
  "Vidheyan": "A submissive migrant worker becomes a terrified, unwilling accomplice to the brutal tyranny and violence of a deeply sadistic local landlord.",
  "Kanchana Sita": "A poetic, mythical retelling of the Ramayana that focuses on the deep psychological trauma and absent presence of Sita during Rama's rule.",
  "Thampu": "A wandering circus arrives in a quiet village, briefly disrupting the monotony of rural life before packing up and leaving behind lingering emotional impacts.",
  "Kummatty": "A mystical, Pied Piper-like figure visits a village and magically transforms the local children into animals, exploring themes of innocence and nature.",
  "Chidambaram": "A deeply poetic exploration of guilt, betrayal, and redemption after a rural estate worker discovers his wife's affair with his friend and employer.",
  "Agraharathil Kazhuthai": "A highly satirical critique of upper-caste Brahmin orthodoxy when a stray donkey is taken in by a professor, leading to chaotic religious misunderstandings.",
  "Cheriyachante Kroorakrityangal": "An obedient, deeply traditional man slowly descends into violence and psychological collapse due to the changing social hierarchies of feudal Kerala.",
  "Amma Ariyan": "A young man travels across Kerala to inform a mother of her son's death, turning into a profound documentary-style political journey.",
  "Koodevide": "A tragic psychological drama about a possessive, jealous school teacher whose obsessive nature leads to the accidental death of his lover's favorite student.",
  "Namukku Parkkan Munthirithoppukal": "A rich vineyard owner falls in love with his neighbor's stepdaughter, fighting against societal expectations and her deeply abusive stepfather to protect her.",
  "Thoovanathumbikal": "A complex, deeply atmospheric romance about a man torn between his pure love for a village girl and his obsessive passion for an enigmatic sex worker.",
  "Njan Gandharvan": "A mesmerizing fantasy romance about a celestial being (Gandharvan) who descends to Earth and falls passionately in love with a mortal woman.",
  "Thakara": "A raw, highly emotional tragedy about a mentally slow young man whose innocent love for a village girl is manipulated and brutally destroyed by society.",
  "Chamaram": "An intense, tragic romance between an older college lecturer and her younger student, challenging social norms and conventional morality.",
  "Vaishali": "An epic, visually stunning adaptation of a Mahabharata episode where a seductress is sent to lure a celibate sage to bring rain to a drought-stricken kingdom.",
  "Amaram": "A deeply emotional family drama about an uneducated fisherman's fierce ambition and ultimate heartbreak regarding his beloved daughter's future and choices.",
  "Pappan Priyappetta Pappan": "A fantastical comedy about a deceased singer whose spirit is mistakenly put into the bodies of various living individuals by the God of Death.",
  "Sandhesam": "A brilliant, timeless political satire focusing on a middle-class family torn apart by the aggressive, opposing political ideologies of two brothers.",
  "Veendum Chila Veetukaryangal": "A heartwarming family drama detailing the ideological clashes and deep bond between a passionate theater-actor father and his pragmatic son.",
  "Manassinakkare": "A grumpy, alienated elderly woman finds a new lease on life and joy when she befriends a cheerful, optimistic young man in her village.",
  "Nokketha Doorathu Kannum Nattu": "A spirited young girl brings immense joy to her grumpy, estranged grandmother's life, while hiding a deeply tragic secret about her own health.",
  "Poovinu Puthiya Poonthennal": "A deaf-mute man becomes the sole protector of an orphaned boy targeted by ruthless killers who murdered his mother.",
  "Manichitrathazhu": "A masterful psychological thriller about a young bride who becomes possessed by the vengeful spirit of an ancient dancer in a haunted ancestral mansion.",
  "Aniyathipraavu": "A highly influential romantic drama detailing the profound struggles of a young interfaith couple facing intense opposition from their respective, deeply loving families.",
  "Chithram": "A desperate father hires a con man to pretend to be his daughter's husband for the sake of his dying father-in-law, leading to unexpected emotional bonds.",
  "Kilukkam": "A hilarious, beloved comedy about a tourist guide and a photographer whose lives are turned upside down by the arrival of a seemingly mentally unstable young woman.",
  "Thenmavin Kombath": "A visually spectacular romantic comedy centered on the fierce rivalry between two close friends who unknowingly fall in love with the same fiery village woman.",
  "Kaalapani": "An epic, harrowing historical drama detailing the brutal, horrific torture faced by Indian independence activists imprisoned in the infamous Cellular Jail in the Andaman Islands.",
  "Thanmatra": "A deeply devastating, highly emotional portrayal of a loving, brilliant government employee and his family's heartbreaking struggle after he is diagnosed with early-onset Alzheimer's.",
  "Pranayam": "A profound, deeply mature exploration of complex love, exploring the intricate emotional dynamics between a woman, her paralyzed husband, and her former lover.",
  "Kalimannu": "A socially relevant, highly controversial drama exploring the deep emotional bond of motherhood and a woman's right to artificial insemination and childbirth.",
  "Aadujeevitham": "Based on a true story, an Indian migrant worker is brutally forced into modern-day slavery, herding goats in the horrific, isolating deserts of Saudi Arabia.",
  "Angamaly Diaries": "A hyper-kinetic, incredibly raw crime drama chronicling the chaotic lives, gang rivalries, and pork business of youths in the bustling town of Angamaly.",
  "Ee.Ma.Yau.": "A deeply atmospheric, darkly comedic tragedy detailing a son's desperate, increasingly chaotic efforts to organize a grand, respectful funeral for his deceased father.",
  "Jallikattu": "A visually astonishing, deeply primal thriller where a village descends into absolute, violent chaos as they attempt to hunt down a wild buffalo that has escaped.",
  "Churuli": "A deeply surreal, mind-bending mystery about two undercover cops who enter a mysterious, foul-mouthed forest village where time, logic, and identity collapse.",
  "Thondimuthalum Driksakshiyum": "A brilliant, highly grounded realistic drama centering on a petty thief who swallows a stolen gold chain, leading to a tense, psychological standoff in a rural police station.",
  "Joji": "A dark, highly cynical modern adaptation of Macbeth set in a wealthy, deeply dysfunctional Kerala plantation family during the COVID-19 pandemic.",
  "Njan Steve Lopez": "A coming-of-age crime drama about an innocent college student whose life spirals out of control when he inadvertently witnesses a violent gang conflict.",
  "Kammatipaadam": "An epic, gritty saga exploring the deep, violent history of real estate mafia and the brutal marginalization of Dalit communities during the rapid urbanization of Kochi.",
  "Kuttavum Shikshayum": "A tense, highly procedural police drama tracking a team of Kerala cops as they travel to a hostile North Indian village to catch a gang of jewelry thieves.",
  "Thuramukham": "A sprawling, deeply political historical epic detailing the intense labor struggles, union conflicts, and profound exploitation of workers at the Mattancherry harbor.",
  "Drishyam": "A brilliant, incredibly tense thriller about a common man who uses knowledge gained from movies to execute an elaborate cover-up after his family accidentally commits a murder.",
  "Drishyam 2": "A masterful sequel where the protagonist must defensively navigate the reopened murder investigation, relying on an even more complex, brilliant long-term strategy.",
  "Kooman": "A psychological thriller about an intensely jealous, highly observant police officer whose obsession with proving his superiority leads him into a deeply dark criminal path.",
  "Neru": "A gripping courtroom drama focusing on a blind sculptor seeking justice after a horrific assault, and the brilliant, deeply strategic lawyer who defends her.",
  "Iyobinte Pusthakam": "A visually spectacular, deeply violent period drama set in the Munnar tea estates, focusing on family betrayal, sibling rivalry, and the changing political landscape of the 1940s.",
  "Varathan": "A highly intense, slow-burn survival thriller where a young urban couple's peaceful retreat to a rural estate turns into a terrifying, violent standoff against local goons.",
  "Bheeshma Parvam": "An epic, incredibly stylish gangster drama about a powerful, deeply respected patriarch who violently defends his family empire from internal betrayal and external enemies.",
  "Bougainvillea": "A suspenseful psychological thriller tracking a deeply troubled family dealing with severe mental trauma and their entanglement in a terrifying, deadly series of mysterious events."
};

let count = 0;
Object.keys(plots).forEach(title => {
    const escapedTitle = title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`("title":\\s*"${escapedTitle}",[\\s\\S]*?)"plot":\\s*"Plot details to be updated."`, 'g');
    if (data.match(regex)) {
        data = data.replace(regex, `$1"plot": "${plots[title]}"`);
        count++;
    }
});

fs.writeFileSync('js/data.js', data, 'utf8');
console.log(`Successfully updated ${count} plots in js/data.js`);
