const fs = require('fs');
const https = require('https');

const API_KEY = '8265bd1679663a7ea12ac168da84d2e8';

const newData = {
    "John Carpenter": [
        { "id": "halloween", "title": "Halloween", "year": 1978, "director": "John Carpenter", "writer": "John Carpenter / Debra Hill", "cinematographer": "Dean Cundey", "editor": "Charles Bornstein / Tommy Lee Wallace", "composer": "John Carpenter", "studio": "Compass International Pictures / Falcon International Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Halloween", "focus": "Groundbreaking Steadicam POV shots, masterclass in wide-screen suspense.", "plot": "Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again.", "releaseDate": "1978-01-01" },
        { "id": "the-thing", "title": "The Thing", "year": 1982, "director": "John Carpenter", "writer": "Bill Lancaster", "cinematographer": "Dean Cundey", "editor": "Todd Ramsay", "composer": "Ennio Morricone", "studio": "Universal Pictures / Turman-Foster Company", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Thing", "focus": "Pioneering, grotesque practical effects, claustrophobic and paranoid framing.", "plot": "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.", "releaseDate": "1982-01-01" },
        { "id": "escape-from-new-york", "title": "Escape from New York", "year": 1981, "director": "John Carpenter", "writer": "John Carpenter / Nick Castle", "cinematographer": "Dean Cundey", "editor": "Todd Ramsay", "composer": "John Carpenter / Alan Howarth", "studio": "Avco Embassy Pictures / International Film Investors / Goldcrest Films", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Escape+from+New+York", "focus": "Dark, ruined urban aesthetic, pioneering use of early wireframe computer graphics.", "plot": "In 1997, when the U.S. president crashes into Manhattan, now a giant maximum security prison, a convicted bank robber is sent in to rescue him.", "releaseDate": "1981-01-01" },
        { "id": "assault-on-precinct-13", "title": "Assault on Precinct 13", "year": 1976, "director": "John Carpenter", "writer": "John Carpenter", "cinematographer": "Douglas Knapp", "editor": "John Carpenter", "composer": "John Carpenter", "studio": "CKY Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Assault+on+Precinct+13", "focus": "Minimalist lighting, deliberate pacing prioritizing tension and atmosphere.", "plot": "A highway patrol officer, two criminals and a station secretary defend a defunct Los Angeles precinct office against a siege by a bloodthirsty street gang.", "releaseDate": "1976-01-01" },
        { "id": "big-trouble-in-little-china", "title": "Big Trouble in Little China", "year": 1986, "director": "John Carpenter", "writer": "Gary Goldman / David Z. Weinstein / W.D. Richter", "cinematographer": "Dean Cundey", "editor": "Mark Warner / Edward A. Warschilka", "composer": "John Carpenter / Alan Howarth", "studio": "Twentieth Century Fox", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Big+Trouble+in+Little+China", "focus": "Kinetic martial arts staging, hyper-colorful mystic lighting, playful subversion of action tropes.", "plot": "A rough-and-tumble trucker helps rescue his friend's fiancé from an ancient sorcerer in a supernatural battle beneath Chinatown.", "releaseDate": "1986-01-01" }
    ],
    "Robert Altman": [
        { "id": "nashville", "title": "Nashville", "year": 1975, "director": "Robert Altman", "writer": "Joan Tewkesbury", "cinematographer": "Paul Lohmann", "editor": "Sidney Levin / Dennis M. Hill", "composer": "Richard Baskin", "studio": "American Broadcasting Companies (ABC) / Paramount Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Nashville", "focus": "Pioneering multi-track overlapping dialogue, massive ensemble staging.", "plot": "Over the course of a few days, the intersecting lives of numerous people involved in the country music business in Nashville, Tennessee are followed.", "releaseDate": "1975-01-01" },
        { "id": "mash", "title": "MASH", "year": 1970, "director": "Robert Altman", "writer": "Ring Lardner Jr.", "cinematographer": "Harold E. Stine", "editor": "Danford B. Greene", "composer": "Johnny Mandel", "studio": "Twentieth Century Fox / Aspen Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=MASH", "focus": "Chaotic, documentarian visual style, deeply cynical and anti-authoritarian tone.", "plot": "The staff of a Korean War field hospital use humor and high jinks to keep their sanity in the face of the horror of war.", "releaseDate": "1970-01-01" },
        { "id": "the-player", "title": "The player", "year": 1992, "director": "Robert Altman", "writer": "Michael Tolkin", "cinematographer": "Jean Lépine", "editor": "Geraldine Peroni", "composer": "Thomas Newman", "studio": "Avenue Pictures / Spelling Entertainment", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Player", "focus": "Famous incredibly complex opening continuous tracking shot, sharp satirical tone.", "plot": "A Hollywood studio executive is being sent death threats by a writer whose script he rejected, but which one?", "releaseDate": "1992-01-01" },
        { "id": "short-cuts", "title": "Short Cuts", "year": 1993, "director": "Robert Altman", "writer": "Robert Altman / Frank Barhydt", "cinematographer": "Walt Lloyd", "editor": "Geraldine Peroni", "composer": "Mark Isham", "studio": "Fine Line Features / Avenue Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Short+Cuts", "focus": "Vast, weaving narrative structure, naturalistic slice-of-life cinematography.", "plot": "The day-to-day lives of several suburban Los Angeles residents.", "releaseDate": "1993-01-01" },
        { "id": "mccabe-mrs-miller", "title": "McCabe & Mrs. Miller", "year": 1971, "director": "Robert Altman", "writer": "Robert Altman / Brian McKay", "cinematographer": "Vilmos Zsigmond", "editor": "Lou Lombardo", "composer": "Leonard Cohen", "studio": "Warner Bros.", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=McCabe+and+Mrs+Miller", "focus": "Hazy, 'flashed' negative photography, muddy realism breaking Western mythology.", "plot": "A gambler and a prostitute become business partners in a remote Old West mining town, and their enterprise thrives until a large corporation arrives on the scene.", "releaseDate": "1971-01-01" }
    ],
    "David Fincher": [
        { "id": "the-social-network", "title": "The Social Network", "year": 2010, "director": "David Fincher", "writer": "Aaron Sorkin", "cinematographer": "Jeff Cronenweth", "editor": "Angus Wall / Kirk Baxter", "composer": "Trent Reznor / Atticus Ross", "studio": "Columbia Pictures / Relativity Media", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Social+Network", "focus": "Clinically precise digital cinematography, low-light framing, rapid-fire pacing.", "plot": "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.", "releaseDate": "2010-01-01" },
        { "id": "fight-club", "title": "Fight Club", "year": 1999, "director": "David Fincher", "writer": "Jim Uhls", "cinematographer": "Jeff Cronenweth", "editor": "James Haygood", "composer": "The Dust Brothers", "studio": "Fox 2000 Pictures / Regency Enterprises", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Fight+Club", "focus": "Grungy, desaturated green/yellow color palette, pioneering CGI transitions.", "plot": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.", "releaseDate": "1999-01-01" },
        { "id": "seven", "title": "Seven (Se7en)", "year": 1995, "director": "David Fincher", "writer": "Andrew Kevin Walker", "cinematographer": "Darius Khondji", "editor": "Richard Francis-Bruce", "composer": "Howard Shore", "studio": "New Line Cinema", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Seven", "focus": "Deep, oppressive shadows, constant rain, bleach bypass film processing.", "plot": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.", "releaseDate": "1995-01-01" },
        { "id": "zodiac", "title": "Zodiac", "year": 2007, "director": "David Fincher", "writer": "James Vanderbilt", "cinematographer": "Harris Savides", "editor": "Angus Wall", "composer": "David Shire", "studio": "Phoenix Pictures / Warner Bros. / Paramount Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Zodiac", "focus": "Pioneering digital workflow, exactingly precise recreations of period locations.", "plot": "Between 1968 and 1983, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer.", "releaseDate": "2007-01-01" },
        { "id": "gone-girl", "title": "Gone Girl", "year": 2014, "director": "David Fincher", "writer": "Gillian Flynn", "cinematographer": "Jeff Cronenweth", "editor": "Kirk Baxter", "composer": "Trent Reznor / Atticus Ross", "studio": "Regency Enterprises / Twentieth Century Fox", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Gone+Girl", "focus": "Cold, detached framing, sickly yellow and sterile blue hues reflecting a toxic marriage.", "plot": "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.", "releaseDate": "2014-01-01" }
    ],
    "Christopher Nolan": [
        { "id": "inception", "title": "Inception", "year": 2010, "director": "Christopher Nolan", "writer": "Christopher Nolan", "cinematographer": "Wally Pfister", "editor": "Lee Smith", "composer": "Hans Zimmer", "studio": "Legendary Pictures / Syncopy", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Inception", "focus": "Monumental practical effects inside surreal, dream-logic architecture, shifting gravity.", "plot": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", "releaseDate": "2010-01-01" },
        { "id": "memento", "title": "Memento", "year": 2000, "director": "Christopher Nolan", "writer": "Christopher Nolan", "cinematographer": "Wally Pfister", "editor": "Dody Dorn", "composer": "David Julyan", "studio": "Team Todd / Newmarket Capital Group", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Memento", "focus": "Non-linear narrative visually separated by color and black-and-white sequences.", "plot": "A man with short-term memory loss attempts to track down his wife's murderer.", "releaseDate": "2000-01-01" },
        { "id": "the-dark-knight", "title": "The Dark Knight", "year": 2008, "director": "Christopher Nolan", "writer": "Jonathan Nolan / Christopher Nolan", "cinematographer": "Wally Pfister", "editor": "Lee Smith", "composer": "Hans Zimmer / James Newton Howard", "studio": "Warner Bros. Pictures / Legendary Pictures / Syncopy", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Dark+Knight", "focus": "Pioneering use of IMAX cameras in feature films, gritty urban realism.", "plot": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", "releaseDate": "2008-01-01" },
        { "id": "interstellar", "title": "Interstellar", "year": 2014, "director": "Christopher Nolan", "writer": "Jonathan Nolan / Christopher Nolan", "cinematographer": "Hoyte van Hoytema", "editor": "Lee Smith", "composer": "Hans Zimmer", "studio": "Paramount Pictures / Warner Bros. / Legendary Pictures / Syncopy", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Interstellar", "focus": "Practical spaceships and sets, vast IMAX vistas conveying unimaginable scale.", "plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "releaseDate": "2014-01-01" },
        { "id": "oppenheimer", "title": "Oppenheimer", "year": 2023, "director": "Christopher Nolan", "writer": "Christopher Nolan", "cinematographer": "Hoyte van Hoytema", "editor": "Jennifer Lame", "composer": "Ludwig Göransson", "studio": "Universal Pictures / Syncopy / Atlas Entertainment", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Oppenheimer", "focus": "Pioneering IMAX black-and-white photography, visceral in-camera atomic effects.", "plot": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", "releaseDate": "2023-01-01" }
    ],
    "Quentin Tarantino": [
        { "id": "pulp-fiction", "title": "Pulp Fiction", "year": 1994, "director": "Quentin Tarantino", "writer": "Quentin Tarantino / Roger Avary", "cinematographer": "Andrzej Sekuła", "editor": "Sally Menke", "composer": "Compiled Surf Rock / Soul", "studio": "A Band Apart / Miramax", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Pulp+Fiction", "focus": "Pop-art aesthetic, highly stylized dialogue-driven long takes.", "plot": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", "releaseDate": "1994-01-01" },
        { "id": "inglourious-basterds", "title": "Inglourious Basterds", "year": 2009, "director": "Quentin Tarantino", "writer": "Quentin Tarantino", "cinematographer": "Robert Richardson", "editor": "Sally Menke", "composer": "Compiled Soundtrack", "studio": "A Band Apart / Studio Babelsberg / The Weinstein Company", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Inglourious+Basterds", "focus": "Operatic tension building, Spaghetti Western visual tropes applied to WWII.", "plot": "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.", "releaseDate": "2009-01-01" },
        { "id": "reservoir-dogs", "title": "Reservoir Dogs", "year": 1992, "director": "Quentin Tarantino", "writer": "Quentin Tarantino", "cinematographer": "Andrzej Sekuła", "editor": "Sally Menke", "composer": "Compiled 1970s Pop", "studio": "Live Entertainment / Dog Eat Dog Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Reservoir+Dogs", "focus": "Confined, theatrical blocking, distinct low-angle 'trunk shots', extreme stylization.", "plot": "When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.", "releaseDate": "1992-01-01" },
        { "id": "kill-bill-vol-1", "title": "Kill Bill: Vol. 1", "year": 2003, "director": "Quentin Tarantino", "writer": "Quentin Tarantino", "cinematographer": "Robert Richardson", "editor": "Sally Menke", "composer": "RZA", "studio": "A Band Apart / Miramax", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Kill+Bill", "focus": "Hyper-stylized pastiche of martial arts, anime, and giallo aesthetics.", "plot": "After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.", "releaseDate": "2003-01-01" },
        { "id": "django-unchained", "title": "Django Unchained", "year": 2012, "director": "Quentin Tarantino", "writer": "Quentin Tarantino", "cinematographer": "Robert Richardson", "editor": "Fred Raskin", "composer": "Compiled Soundtrack", "studio": "A Band Apart / Columbia Pictures / The Weinstein Company", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Django+Unchained", "focus": "Brutal, stylized violence framed against lush, epic Southern landscapes.", "plot": "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.", "releaseDate": "2012-01-01" }
    ],
    "Paul Thomas Anderson": [
        { "id": "there-will-be-blood", "title": "There Will Be Blood", "year": 2007, "director": "Paul Thomas Anderson", "writer": "Paul Thomas Anderson", "cinematographer": "Robert Elswit", "editor": "Dylan Tichenor", "composer": "Jonny Greenwood", "studio": "Ghoulardi Film Company / Paramount Vantage / Miramax", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=There+Will+Be+Blood", "focus": "Stark, oppressive landscapes, meticulously composed tracking shots, apocalyptic lighting.", "plot": "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.", "releaseDate": "2007-01-01" },
        { "id": "magnolia", "title": "Magnolia", "year": 1999, "director": "Paul Thomas Anderson", "writer": "Paul Thomas Anderson", "cinematographer": "Robert Elswit", "editor": "Dylan Tichenor", "composer": "Jon Brion", "studio": "Ghoulardi Film Company / New Line Cinema", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Magnolia", "focus": "Relentless, swirling Steadicam choreography connecting sprawling ensemble narratives.", "plot": "An epic mosaic of interrelated characters in search of love, forgiveness, and meaning in the San Fernando Valley.", "releaseDate": "1999-01-01" },
        { "id": "boogie-nights", "title": "Boogie Nights", "year": 1997, "director": "Paul Thomas Anderson", "writer": "Paul Thomas Anderson", "cinematographer": "Robert Elswit", "editor": "Dylan Tichenor", "composer": "Michael Penn", "studio": "Ghoulardi Film Company / New Line Cinema", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Boogie+Nights", "focus": "Vibrant, kinetic long takes capturing the colorful excess of the 1970s adult film industry.", "plot": "The story of a young man's adventures in the Californian pornography industry of the late 1970s and early 1980s.", "releaseDate": "1997-01-01" },
        { "id": "the-master", "title": "The Master", "year": 2012, "director": "Paul Thomas Anderson", "writer": "Paul Thomas Anderson", "cinematographer": "Mihai Mălaimare Jr.", "editor": "Leslie Jones / Peter McNulty", "composer": "Jonny Greenwood", "studio": "Ghoulardi Film Company / Annapurna Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Master", "focus": "Shot on 65mm film, intensely shallow depth of field, painterly ocean lighting.", "plot": "A Naval veteran arrives home from war unsettled and uncertain of his future - until he is tantalized by The Cause and its charismatic leader.", "releaseDate": "2012-01-01" },
        { "id": "phantom-thread", "title": "Phantom Thread", "year": 2017, "director": "Paul Thomas Anderson", "writer": "Paul Thomas Anderson", "cinematographer": "Paul Thomas Anderson (Uncredited)", "editor": "Dylan Tichenor", "composer": "Jonny Greenwood", "studio": "Ghoulardi Film Company / Annapurna Pictures / Focus Features", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Phantom+Thread", "focus": "Soft, hazy, claustrophobic elegance capturing the toxic perfectionism of high fashion.", "plot": "Set in 1950s London, Reynolds Woodcock is a renowned dressmaker whose fastidious life is disrupted by a young, strong-willed woman, Alma, who becomes his muse and lover.", "releaseDate": "2017-01-01" }
    ],
    "Coen Brothers": [
        { "id": "no-country-for-old-men", "title": "No Country for Old Men", "year": 2007, "director": "Joel Coen / Ethan Coen", "writer": "Joel Coen / Ethan Coen", "cinematographer": "Roger Deakins", "editor": "Roderick Jaynes", "composer": "Carter Burwell", "studio": "Scott Rudin Productions / Paramount Vantage / Miramax", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=No+Country+for+Old+Men", "focus": "Stark, unromanticized West Texas landscapes, incredibly tense and precise framing.", "plot": "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.", "releaseDate": "2007-01-01" },
        { "id": "fargo", "title": "Fargo", "year": 1996, "director": "Joel Coen / Ethan Coen", "writer": "Joel Coen / Ethan Coen", "cinematographer": "Roger Deakins", "editor": "Roderick Jaynes", "composer": "Carter Burwell", "studio": "Working Title Films", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Fargo", "focus": "Blinding, oppressive white snowscapes isolating small, absurd human tragedies.", "plot": "Jerry Lundegaard's inept crime falls apart due to his and his henchmen's bungling and the persistent police work of the quite pregnant Marge Gunderson.", "releaseDate": "1996-01-01" },
        { "id": "the-big-lebowski", "title": "The Big Lebowski", "year": 1998, "director": "Joel Coen / Ethan Coen", "writer": "Joel Coen / Ethan Coen", "cinematographer": "Roger Deakins", "editor": "Roderick Jaynes", "composer": "Carter Burwell", "studio": "Working Title Films / PolyGram Filmed Entertainment", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Big+Lebowski", "focus": "Wide-angle absurdity, surrealistic Busby Berkeley-style dream sequences.", "plot": "Ultimate L.A. slacker Jeff \"The Dude\" Lebowski, mistaken for a millionaire of the same name, seeks restitution for a rug ruined by debt collectors.", "releaseDate": "1998-01-01" },
        { "id": "millers-crossing", "title": "Miller's Crossing", "year": 1990, "director": "Joel Coen / Ethan Coen", "writer": "Joel Coen / Ethan Coen", "cinematographer": "Barry Sonnenfeld", "editor": "Michael R. Miller", "composer": "Carter Burwell", "studio": "Circle Films", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Millers+Crossing", "focus": "Lush, autumnal woodland cinematography contrasting violent gangster machinations.", "plot": "Tom Reagan, an advisor to a Prohibition-era crime boss, tries to keep the peace between warring mobs but gets caught in divided loyalties.", "releaseDate": "1990-01-01" },
        { "id": "inside-llewyn-davis", "title": "Inside Llewyn Davis", "year": 2013, "director": "Joel Coen / Ethan Coen", "writer": "Joel Coen / Ethan Coen", "cinematographer": "Bruno Delbonnel", "editor": "Roderick Jaynes", "composer": "T Bone Burnett", "studio": "Scott Rudin Productions / StudioCanal", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Inside+Llewyn+Davis", "focus": "Muted, desaturated, soft-light capturing the melancholic, cyclical struggle of an artist.", "plot": "A week in the life of a young singer as he navigates the Greenwich Village folk scene of 1961.", "releaseDate": "2013-01-01" }
    ],
    "James Cameron": [
        { "id": "the-terminator", "title": "The Terminator", "year": 1984, "director": "James Cameron", "writer": "James Cameron / Gale Anne Hurd", "cinematographer": "Adam Greenberg", "editor": "Mark Goldblatt", "composer": "Brad Fiedel", "studio": "Hemdale Film Corporation / Pacific Western Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Terminator", "focus": "Cold, neon-lit tech noir, relentless pacing and masterful low-budget practical effects.", "plot": "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's future salvation.", "releaseDate": "1984-01-01" },
        { "id": "terminator-2", "title": "Terminator 2: Judgment Day", "year": 1991, "director": "James Cameron", "writer": "James Cameron / William Wisher", "cinematographer": "Adam Greenberg", "editor": "Conrad Buff / Richard A. Harris / Mark Goldblatt", "composer": "Brad Fiedel", "studio": "Carolco Pictures / Pacific Western Productions / Lightstorm Entertainment", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Terminator+2", "focus": "Revolutionary liquid-metal CGI seamlessly blended with epic-scale practical action.", "plot": "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.", "releaseDate": "1991-01-01" },
        { "id": "aliens", "title": "Aliens", "year": 1986, "director": "James Cameron", "writer": "James Cameron", "cinematographer": "Adrian Biddle", "editor": "Ray Lovejoy", "composer": "James Horner", "studio": "Brandywine Productions / Twentieth Century Fox", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Aliens", "focus": "Industrial, gritty, blue-hued sci-fi action staging, relentless tension building.", "plot": "Fifty-seven years after surviving an apocalyptic attack aboard her space vessel by merciless space creatures, Officer Ripley awakens from hyper-sleep and tries to warn anyone who will listen about the predators.", "releaseDate": "1986-01-01" },
        { "id": "titanic", "title": "Titanic", "year": 1997, "director": "James Cameron", "writer": "James Cameron", "cinematographer": "Russell Carpenter", "editor": "Conrad Buff / James Cameron / Richard A. Harris", "composer": "James Horner", "studio": "Paramount Pictures / Twentieth Century Fox / Lightstorm Entertainment", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Titanic", "focus": "Monumental practical set pieces, sweeping epic romance framed against technological disaster.", "plot": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", "releaseDate": "1997-01-01" },
        { "id": "avatar", "title": "Avatar", "year": 2009, "director": "James Cameron", "writer": "James Cameron", "cinematographer": "Mauro Fiore", "editor": "James Cameron / John Refoua / Stephen E. Rivkin", "composer": "James Horner", "studio": "Lightstorm Entertainment / Twentieth Century Fox", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Avatar", "focus": "Pioneering 3D motion-capture technology, lush bioluminescent world-building.", "plot": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.", "releaseDate": "2009-01-01" }
    ],
    "Ridley Scott": [
        { "id": "blade-runner", "title": "Blade Runner", "year": 1982, "director": "Ridley Scott", "writer": "Hampton Fancher / David Peoples", "cinematographer": "Jordan Cronenweth", "editor": "Marsha Nakashima / Terry Rawlings", "composer": "Vangelis", "studio": "The Ladd Company / Shaw Brothers / Warner Bros.", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Blade+Runner", "focus": "Defining cyberpunk aesthetic; neon, rain, smoke, and suffocating corporate dystopia.", "plot": "A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.", "releaseDate": "1982-01-01" },
        { "id": "alien", "title": "Alien", "year": 1979, "director": "Ridley Scott", "writer": "Dan O'Bannon", "cinematographer": "Derek Vanlint", "editor": "Terry Rawlings / Peter Weatherley", "composer": "Jerry Goldsmith", "studio": "Brandywine Productions / Twentieth Century Fox", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Alien", "focus": "Claustrophobic, grimy industrial spaceship design concealing biomechanical horror.", "plot": "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.", "releaseDate": "1979-01-01" },
        { "id": "gladiator", "title": "Gladiator", "year": 2000, "director": "Ridley Scott", "writer": "David Franzoni / John Logan / William Nicholson", "cinematographer": "John Mathieson", "editor": "Pietro Scalia", "composer": "Hans Zimmer / Lisa Gerrard", "studio": "Douglas Wick Productions / Scott Free Productions / Universal Pictures / DreamWorks Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Gladiator", "focus": "Sweeping, sun-drenched historical epic scale, visceral high-shutter-speed combat.", "plot": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", "releaseDate": "2000-01-01" },
        { "id": "thelma-louise", "title": "Thelma & Louise", "year": 1991, "director": "Ridley Scott", "writer": "Callie Khouri", "cinematographer": "Adrian Biddle", "editor": "Thom Noble", "composer": "Hans Zimmer", "studio": "Pathé Entertainment / Percy Main Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Thelma+and+Louise", "focus": "Expansive, dusty American Southwest vistas emphasizing freedom and tragic momentum.", "plot": "Two best friends set out on an adventure, but it soon turns around to a terrifying escape from being hunted by the police, as these two girls escape for the crimes they committed.", "releaseDate": "1991-01-01" },
        { "id": "black-hawk-down", "title": "Black Hawk Down", "year": 2001, "director": "Ridley Scott", "writer": "Ken Nolan", "cinematographer": "John Mathieson", "editor": "Pietro Scalia", "composer": "Hans Zimmer", "studio": "Revolution Studios / Jerry Bruckheimer Films / Scott Free Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Black+Hawk+Down", "focus": "Relentless, chaotic, documentary-style combat cinematography with stylized grading.", "plot": "160 elite U.S. soldiers drop into Somalia to capture two top lieutenants of a renegade warlord and find themselves in a desperate battle with a large force of heavily-armed Somalis.", "releaseDate": "2001-01-01" }
    ],
    "Michael Mann": [
        { "id": "heat", "title": "Heat", "year": 1995, "director": "Michael Mann", "writer": "Michael Mann", "cinematographer": "Dante Spinotti", "editor": "Dov Hoenig / Pasquale Buba / William Goldenberg / Tom Rolf", "composer": "Elliot Goldenthal", "studio": "Forward Pass / Regency Enterprises", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Heat", "focus": "Sleek, cool-blue nocturnal cityscapes, hyper-realistic urban combat staging.", "plot": "A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.", "releaseDate": "1995-01-01" },
        { "id": "the-insider", "title": "The Insider", "year": 1999, "director": "Michael Mann", "writer": "Eric Roth / Michael Mann", "cinematographer": "Dante Spinotti", "editor": "William Goldenberg / Paul Rubell / David Rosenbloom", "composer": "Pieter Bourke / Lisa Gerrard", "studio": "Touchstone Pictures / Forward Pass", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Insider", "focus": "Intensely claustrophobic close-ups capturing psychological paranoia and corporate dread.", "plot": "A research chemist comes under personal and professional attack when he decides to appear on a \"60 Minutes\" expose on Big Tobacco.", "releaseDate": "1999-01-01" },
        { "id": "thief", "title": "Thief", "year": 1981, "director": "Michael Mann", "writer": "Michael Mann", "cinematographer": "Donald E. Thorin", "editor": "Dov Hoenig", "composer": "Tangerine Dream", "studio": "Michael Mann Productions / Caan Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Thief", "focus": "Wet, neon-soaked Chicago streets, meticulous attention to professional process.", "plot": "A highly skilled jewel thief operates to his own strict code, but after his fence is killed he is forced to do a job for the Chicago mafia.", "releaseDate": "1981-01-01" },
        { "id": "collateral", "title": "Collateral", "year": 2004, "director": "Michael Mann", "writer": "Stuart Beattie", "cinematographer": "Dion Beebe / Paul Cameron", "editor": "Jim Miller / Paul Rubell", "composer": "James Newton Howard", "studio": "Parkes/MacDonald Productions / Edge City / Paramount Pictures / DreamWorks Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Collateral", "focus": "Pioneering use of low-light digital video to capture the gritty, sodium-lit LA night.", "plot": "A cab driver finds himself the hostage of an engaging contract killer as he makes his rounds from hit to hit during one night in Los Angeles.", "releaseDate": "2004-01-01" },
        { "id": "manhunter", "title": "Manhunter", "year": 1986, "director": "Michael Mann", "writer": "Michael Mann", "cinematographer": "Dante Spinotti", "editor": "Dov Hoenig", "composer": "Michel Rubini / The Prime Moves", "studio": "De Laurentiis Entertainment Group", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Manhunter", "focus": "Striking, hyper-stylized architectural framing and aggressive use of stark white/blue color palettes.", "plot": "Former FBI profiler Will Graham returns to service to pursue a deranged serial killer named \"the Tooth Fairy\" by the media.", "releaseDate": "1986-01-01" }
    ],
    "Robert Zemeckis": [
        { "id": "back-to-the-future", "title": "Back to the Future", "year": 1985, "director": "Robert Zemeckis", "writer": "Robert Zemeckis / Bob Gale", "cinematographer": "Dean Cundey", "editor": "Arthur Schmidt / Harry Keramidas", "composer": "Alan Silvestri", "studio": "Amblin Entertainment / Universal Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Back+to+the+Future", "focus": "Kinetic, incredibly tight narrative pacing, seamless integration of early visual effects.", "plot": "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.", "releaseDate": "1985-01-01" },
        { "id": "forrest-gump", "title": "Forrest Gump", "year": 1994, "director": "Robert Zemeckis", "writer": "Eric Roth", "cinematographer": "Don Burgess", "editor": "Arthur Schmidt", "composer": "Alan Silvestri", "studio": "Wendy Finerman Productions / Paramount Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Forrest+Gump", "focus": "Groundbreaking invisible CGI integrating the protagonist into historical footage.", "plot": "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75.", "releaseDate": "1994-01-01" },
        { "id": "who-framed-roger-rabbit", "title": "Who Framed Roger Rabbit", "year": 1988, "director": "Robert Zemeckis", "writer": "Jeffrey Price / Peter S. Seaman", "cinematographer": "Dean Cundey", "editor": "Arthur Schmidt", "composer": "Alan Silvestri", "studio": "Amblin Entertainment / Touchstone Pictures / Silver Screen Partners III", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Roger+Rabbit", "focus": "Technically astonishing blend of live-action film noir cinematography and 2D hand-drawn animation.", "plot": "A toon-hating detective is a cartoon rabbit's only hope to prove his innocence when he is accused of murder.", "releaseDate": "1988-01-01" },
        { "id": "cast-away", "title": "Cast Away", "year": 2000, "director": "Robert Zemeckis", "writer": "William Broyles Jr.", "cinematographer": "Don Burgess", "editor": "Arthur Schmidt", "composer": "Alan Silvestri", "studio": "ImageMovers / Playtone / Twentieth Century Fox / DreamWorks Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Cast+Away", "focus": "Starkly quiet, prolonged sequences lacking a musical score to emphasize utter isolation.", "plot": "A FedEx executive undergoes a physical and emotional transformation after crash landing on a deserted island.", "releaseDate": "2000-01-01" },
        { "id": "contact", "title": "Contact", "year": 1997, "director": "Robert Zemeckis", "writer": "James V. Hart / Michael Goldenberg", "cinematographer": "Don Burgess", "editor": "Arthur Schmidt", "composer": "Alan Silvestri", "studio": "SouthSide Amusement Company / Warner Bros.", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Contact", "focus": "Sweeping conceptual camera moves highlighting scale and philosophical wonder.", "plot": "Dr. Ellie Arroway, after years of searching, finds conclusive radio proof of extraterrestrial intelligence, sending plans for a mysterious machine.", "releaseDate": "1997-01-01" }
    ],
    "David Lynch": [
        { "id": "mulholland-drive", "title": "Mulholland Drive", "year": 2001, "director": "David Lynch", "writer": "David Lynch", "cinematographer": "Peter Deming", "editor": "Mary Sweeney", "composer": "Angelo Badalamenti", "studio": "Les Films Alain Sarde / Asymmetrical Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Mulholland+Drive", "focus": "Dream-logic narrative structure, deeply unsettling sound design, surreal LA noir.", "plot": "After a car wreck on the winding Mulholland Drive renders a woman amnesiac, she and a perky Hollywood-hopeful search for clues and answers across Los Angeles.", "releaseDate": "2001-01-01" },
        { "id": "blue-velvet", "title": "Blue Velvet", "year": 1986, "director": "David Lynch", "writer": "David Lynch", "cinematographer": "Frederick Elmes", "editor": "Duwayne Dunham", "composer": "Angelo Badalamenti", "studio": "De Laurentiis Entertainment Group", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Blue+Velvet", "focus": "Hyper-saturated 'perfect' suburbia juxtaposed with intensely dark, grotesque underworlds.", "plot": "The discovery of a severed human ear found in a field leads a young man on an investigation related to a beautiful, mysterious nightclub singer and a group of psychopathic criminals.", "releaseDate": "1986-01-01" },
        { "id": "eraserhead", "title": "Eraserhead", "year": 1977, "director": "David Lynch", "writer": "David Lynch", "cinematographer": "Herbert Cardwell / Frederick Elmes", "editor": "David Lynch", "composer": "David Lynch / Alan Splet", "studio": "AFI Conservatory", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Eraserhead", "focus": "Industrial nightmare aesthetic, profound texture, revolutionary ambient soundscape.", "plot": "Henry Spencer tries to survive his industrial environment, his angry girlfriend, and the unbearable screams of his newly born mutant child.", "releaseDate": "1977-01-01" },
        { "id": "the-elephant-man", "title": "The Elephant Man", "year": 1980, "director": "David Lynch", "writer": "Christopher De Vore / Eric Bergren / David Lynch", "cinematographer": "Freddie Francis", "editor": "Anne V. Coates", "composer": "John Morris", "studio": "Brooksfilms", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Elephant+Man", "focus": "Gorgeous, evocative black-and-white photography emphasizing profound humanity and industrial horror.", "plot": "A Victorian surgeon rescues a heavily disfigured man who is mistreated while scraping a living as a side-show freak.", "releaseDate": "1980-01-01" },
        { "id": "lost-highway", "title": "Lost Highway", "year": 1997, "director": "David Lynch", "writer": "David Lynch / Barry Gifford", "cinematographer": "Peter Deming", "editor": "Mary Sweeney", "composer": "Angelo Badalamenti", "studio": "Asymmetrical Productions / Ciby 2000", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Lost+Highway", "focus": "Pitch-black, oppressive shadows, non-linear psychological dissociation.", "plot": "Anonymous videotapes presage a musician's murder conviction, and a gangster's girlfriend leads a mechanic astray.", "releaseDate": "1997-01-01" }
    ],
    "Wes Anderson": [
        { "id": "grand-budapest-hotel", "title": "The Grand Budapest Hotel", "year": 2014, "director": "Wes Anderson", "writer": "Wes Anderson", "cinematographer": "Robert Yeoman", "editor": "Barney Pilling", "composer": "Alexandre Desplat", "studio": "American Empirical Pictures / Indian Paintbrush / Studio Babelsberg", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Grand+Budapest+Hotel", "focus": "Rigorous symmetry, distinct aspect ratios for different time periods, pastel palette.", "plot": "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years.", "releaseDate": "2014-01-01" },
        { "id": "royal-tenenbaums", "title": "The Royal Tenenbaums", "year": 2001, "director": "Wes Anderson", "writer": "Wes Anderson / Owen Wilson", "cinematographer": "Robert Yeoman", "editor": "Dylan Tichenor", "composer": "Mark Mothersbaugh", "studio": "American Empirical Pictures / Touchstone Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Royal+Tenenbaums", "focus": "Meticulously designed, dollhouse-like cross-sections, warm nostalgic autumnal tones.", "plot": "The eccentric members of a dysfunctional family reluctantly gather under the same roof for various reasons.", "releaseDate": "2001-01-01" },
        { "id": "rushmore", "title": "Rushmore", "year": 1998, "director": "Wes Anderson", "writer": "Wes Anderson / Owen Wilson", "cinematographer": "Robert Yeoman", "editor": "David Moritz", "composer": "Mark Mothersbaugh", "studio": "American Empirical Pictures / Touchstone Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Rushmore", "focus": "Theatrical framing, distinct chapter breaks, introducing his signature deadpan visual style.", "plot": "The extracurricular king of Rushmore preparatory school is put on academic probation.", "releaseDate": "1998-01-01" },
        { "id": "moonrise-kingdom", "title": "Moonrise Kingdom", "year": 2012, "director": "Wes Anderson", "writer": "Wes Anderson / Roman Coppola", "cinematographer": "Robert Yeoman", "editor": "Andrew Weisblum", "composer": "Alexandre Desplat", "studio": "American Empirical Pictures / Indian Paintbrush", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Moonrise+Kingdom", "focus": "Painterly, yellow-tinted nostalgic aesthetic, highly choreographed tracking shots.", "plot": "Two 12-year-olds fall in love, make a secret pact, and run away together into the wilderness.", "releaseDate": "2012-01-01" },
        { "id": "fantastic-mr-fox", "title": "Fantastic Mr. Fox", "year": 2009, "director": "Wes Anderson", "writer": "Wes Anderson / Noah Baumbach", "cinematographer": "Tristan Oliver", "editor": "Andrew Weisblum", "composer": "Alexandre Desplat", "studio": "American Empirical Pictures / Indian Paintbrush / Regency Enterprises", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Fantastic+Mr.+Fox", "focus": "Painstakingly detailed stop-motion animation maintaining signature planar composition.", "plot": "An urbane fox cannot resist returning to his farm raiding ways and then must help his community survive the farmers' retaliation.", "releaseDate": "2009-01-01" }
    ],
    "Denis Villeneuve": [
        { "id": "sicario", "title": "Sicario", "year": 2015, "director": "Denis Villeneuve", "writer": "Taylor Sheridan", "cinematographer": "Roger Deakins", "editor": "Joe Walker", "composer": "Jóhann Jóhannsson", "studio": "Legendary Pictures / Black Label Media", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Sicario", "focus": "Pulsating tension, stark aerial shots of the border, incredibly menacing shadows.", "plot": "An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.", "releaseDate": "2015-01-01" },
        { "id": "arrival", "title": "Arrival", "year": 2016, "director": "Denis Villeneuve", "writer": "Eric Heisserer", "cinematographer": "Bradford Young", "editor": "Joe Walker", "composer": "Jóhann Jóhannsson", "studio": "FilmNation Entertainment / Lava Bear Films", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Arrival", "focus": "Intentionally gloomy, atmospheric framing emphasizing awe, communication, and intellect.", "plot": "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.", "releaseDate": "2016-01-01" },
        { "id": "blade-runner-2049", "title": "Blade Runner 2049", "year": 2017, "director": "Denis Villeneuve", "writer": "Hampton Fancher / Michael Green", "cinematographer": "Roger Deakins", "editor": "Joe Walker", "composer": "Hans Zimmer / Benjamin Wallfisch", "studio": "Alcon Entertainment / Columbia Pictures / Ridley Scott Associates", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Blade+Runner+2049", "focus": "Monumental scale, oppressive orange dustscapes, awe-inspiring brutalist geometry.", "plot": "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.", "releaseDate": "2017-01-01" },
        { "id": "incendies", "title": "Incendies", "year": 2010, "director": "Denis Villeneuve", "writer": "Denis Villeneuve / Valérie Beaugrand-Champagne", "cinematographer": "André Turpin", "editor": "Monique Dartonne", "composer": "Grégoire Hetzel", "studio": "Micro_scope", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Incendies", "focus": "Harsh, unyielding realism, devastating emotional reveals conveyed through sparse visuals.", "plot": "Twins journey to the Middle East to discover their family history and fulfill their mother's last wishes.", "releaseDate": "2010-01-01" },
        { "id": "dune-part-two", "title": "Dune: Part Two", "year": 2024, "director": "Denis Villeneuve", "writer": "Denis Villeneuve / Jon Spaihts", "cinematographer": "Greig Fraser", "editor": "Joe Walker", "composer": "Hans Zimmer", "studio": "Legendary Pictures / Warner Bros. Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Dune+Part+Two", "focus": "Colossal IMAX framing, striking infrared black-and-white sequences, overwhelming scale.", "plot": "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.", "releaseDate": "2024-01-01" }
    ],
    "Damien Chazelle": [
        { "id": "whiplash", "title": "Whiplash", "year": 2014, "director": "Damien Chazelle", "writer": "Damien Chazelle", "cinematographer": "Sharone Meir", "editor": "Tom Cross", "composer": "Justin Hurwitz", "studio": "Bold Films / Blumhouse Productions / Right of Way Films", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Whiplash", "focus": "Aggressive, kinetic editing cut perfectly to the frantic rhythm of jazz drumming.", "plot": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.", "releaseDate": "2014-01-01" },
        { "id": "la-la-land", "title": "La La Land", "year": 2016, "director": "Damien Chazelle", "writer": "Damien Chazelle", "cinematographer": "Linus Sandgren", "editor": "Tom Cross", "composer": "Justin Hurwitz", "studio": "Gilbert Films / Impostor Pictures / Marc Platt Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=La+La+Land", "focus": "Vibrant technicolor aesthetics, sweeping romantic long takes and complex musical choreography.", "plot": "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.", "releaseDate": "2016-01-01" },
        { "id": "first-man", "title": "First Man", "year": 2018, "director": "Damien Chazelle", "writer": "Josh Singer", "cinematographer": "Linus Sandgren", "editor": "Tom Cross", "composer": "Justin Hurwitz", "studio": "Temple Hill Entertainment / Perfect World Pictures / Universal Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=First+Man", "focus": "Claustrophobic, shaky-cam verite in capsules juxtaposed with silent, immense lunar IMAX shots.", "plot": "A look at the life of the astronaut, Neil Armstrong, and the legendary space mission that led him to become the first man to walk on the Moon.", "releaseDate": "2018-01-01" },
        { "id": "babylon", "title": "Babylon", "year": 2022, "director": "Damien Chazelle", "writer": "Damien Chazelle", "cinematographer": "Linus Sandgren", "editor": "Tom Cross", "composer": "Justin Hurwitz", "studio": "Marc Platt Productions / Wild Chickens / Paramount Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Babylon", "focus": "Hyper-kinetic, sweat-drenched, chaotic camera movements capturing roaring twenties excess.", "plot": "A tale of outsized ambition and outrageous excess, it traces the rise and fall of multiple characters during an era of unbridled decadence and depravity in early Hollywood.", "releaseDate": "2022-01-01" },
        { "id": "guy-and-madeline", "title": "Guy and Madeline on a Park Bench", "year": 2009, "director": "Damien Chazelle", "writer": "Damien Chazelle", "cinematographer": "Damien Chazelle", "editor": "Damien Chazelle", "composer": "Justin Hurwitz", "studio": "Harvard University", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Guy+and+Madeline", "focus": "Gritty 16mm black-and-white, raw indie energy capturing spontaneous jazz rhythms.", "plot": "A jazz trumpeter and an introverted woman meet and fall in love in Boston.", "releaseDate": "2009-01-01" }
    ],
    "Alejandro G. Iñárritu": [
        { "id": "birdman", "title": "Birdman", "year": 2014, "director": "Alejandro G. Iñárritu", "writer": "Alejandro G. Iñárritu / Nicolás Giacobone / Alexander Dinelaris Jr. / Armando Bó", "cinematographer": "Emmanuel Lubezki", "editor": "Douglas Crise / Stephen Mirrione", "composer": "Antonio Sánchez", "studio": "New Regency Pictures / M Prods / Le Grisbi Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Birdman", "focus": "A dazzling technical feat, stitched together to appear as one continuous fluid tracking shot.", "plot": "A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.", "releaseDate": "2014-01-01" },
        { "id": "amores-perros", "title": "Amores Perros", "year": 2000, "director": "Alejandro G. Iñárritu", "writer": "Guillermo Arriaga", "cinematographer": "Rodrigo Prieto", "editor": "Alejandro G. Iñárritu / Luis Carballar / Fernando Pérez Unda", "composer": "Gustavo Santaolalla", "studio": "Altavista Films / Zeta Film", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Amores+Perros", "focus": "Gritty, high-contrast, kinetic handheld camera work linking desperate interwoven narratives.", "plot": "A horrific car accident connects three stories, each involving characters dealing with loss, regret, and life's harsh realities, all in the name of love.", "releaseDate": "2000-01-01" },
        { "id": "the-revenant", "title": "The Revenant", "year": 2015, "director": "Alejandro G. Iñárritu", "writer": "Mark L. Smith / Alejandro G. Iñárritu", "cinematographer": "Emmanuel Lubezki", "editor": "Stephen Mirrione", "composer": "Ryūichi Sakamoto / Alva Noto", "studio": "New Regency Pictures / Anonymous Content / Appian Way Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Revenant", "focus": "Shot exclusively with natural light in freezing conditions, incredibly immersive wide-angle lenses.", "plot": "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.", "releaseDate": "2015-01-01" },
        { "id": "21-grams", "title": "21 Grams", "year": 2003, "director": "Alejandro G. Iñárritu", "writer": "Guillermo Arriaga", "cinematographer": "Rodrigo Prieto", "editor": "Stephen Mirrione", "composer": "Gustavo Santaolalla", "studio": "This Is That Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=21+Grams", "focus": "Extremely fragmented, non-linear editing utilizing stark, bleak, grainy textures.", "plot": "A freak accident brings together a critically ill mathematician, a grieving mother, and a born-again ex-con.", "releaseDate": "2003-01-01" },
        { "id": "babel", "title": "Babel", "year": 2006, "director": "Alejandro G. Iñárritu", "writer": "Guillermo Arriaga", "cinematographer": "Rodrigo Prieto", "editor": "Stephen Mirrione", "composer": "Gustavo Santaolalla", "studio": "Anonymous Content / Zeta Film / Central Films", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Babel", "focus": "Vast global scale, emphasizing cultural isolation through varied cinematic textures.", "plot": "Tragedy strikes a married couple on vacation in the Moroccan desert, touching off an interlocking story involving four different families.", "releaseDate": "2006-01-01" }
    ],
    "Darren Aronofsky": [
        { "id": "requiem-for-a-dream", "title": "Requiem for a Dream", "year": 2000, "director": "Darren Aronofsky", "writer": "Hubert Selby Jr. / Darren Aronofsky", "cinematographer": "Matthew Libatique", "editor": "Jay Rabinowitz", "composer": "Clint Mansell", "studio": "Sensation Films / Truth and Soul Prods", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Requiem+for+a+Dream", "focus": "Frenetic hip-hop montages, SnorriCam shots inducing severe psychological claustrophobia.", "plot": "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.", "releaseDate": "2000-01-01" },
        { "id": "black-swan", "title": "Black Swan", "year": 2010, "director": "Darren Aronofsky", "writer": "Mark Heyman / Andrés Heinz / John McLaughlin", "cinematographer": "Matthew Libatique", "editor": "Andrew Weisblum", "composer": "Clint Mansell", "studio": "Cross Creek Pictures / Phoenix Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Black+Swan", "focus": "Visceral, handheld, subjective camerawork emphasizing paranoia and body horror.", "plot": "A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky's \"Swan Lake\".", "releaseDate": "2010-01-01" },
        { "id": "pi", "title": "Pi", "year": 1998, "director": "Darren Aronofsky", "writer": "Darren Aronofsky", "cinematographer": "Matthew Libatique", "editor": "Oren Sarch", "composer": "Clint Mansell", "studio": "Protozoa Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Pi", "focus": "Ultra-high contrast black-and-white reversal film capturing severe mental breakdown.", "plot": "A paranoid mathematician searches for a key number that will unlock the universal patterns found in nature.", "releaseDate": "1998-01-01" },
        { "id": "the-wrestler", "title": "The Wrestler", "year": 2008, "director": "Darren Aronofsky", "writer": "Robert Siegel", "cinematographer": "Maryse Alberti", "editor": "Andrew Weisblum", "composer": "Clint Mansell", "studio": "Protozoa Pictures / Wild Bunch", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Wrestler", "focus": "Documentary-like handheld following shots, unglamorous, deeply empathetic lighting.", "plot": "A faded professional wrestler must retire, but finds his quest for a new life outside the ring a dispiriting struggle.", "releaseDate": "2008-01-01" },
        { "id": "the-whale", "title": "The Whale", "year": 2022, "director": "Darren Aronofsky", "writer": "Samuel D. Hunter", "cinematographer": "Matthew Libatique", "editor": "Andrew Weisblum", "composer": "Rob Simonsen", "studio": "Protozoa Pictures / A24", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=The+Whale", "focus": "Claustrophobic 4:3 aspect ratio trapping the viewer within a single apartment.", "plot": "A reclusive, morbidly obese English teacher attempts to reconnect with his estranged teenage daughter.", "releaseDate": "2022-01-01" }
    ],
    "Jordan Peele": [
        { "id": "get-out", "title": "Get Out", "year": 2017, "director": "Jordan Peele", "writer": "Jordan Peele", "cinematographer": "Toby Oliver", "editor": "Gregory Plotkin", "composer": "Michael Abels", "studio": "Blumhouse Productions / QC Entertainment", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Get+Out", "focus": "Subtle visual unsettling through 'The Sunken Place' aesthetics and stark framing.", "plot": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.", "releaseDate": "2017-01-01" },
        { "id": "us", "title": "Us", "year": 2019, "director": "Jordan Peele", "writer": "Jordan Peele", "cinematographer": "Mike Gioulakis", "editor": "Nicholas Monsour", "composer": "Michael Abels", "studio": "Monkeypaw Productions / Perfect World Pictures", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Us", "focus": "Chilling use of shadows and duality in composition, intense close-ups of doppelgängers.", "plot": "A family's serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them.", "releaseDate": "2019-01-01" },
        { "id": "nope", "title": "Nope", "year": 2022, "director": "Jordan Peele", "writer": "Jordan Peele", "cinematographer": "Hoyte van Hoytema", "editor": "Nicholas Monsour", "composer": "Michael Abels", "studio": "Monkeypaw Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Nope", "focus": "Groundbreaking 'day-for-night' IMAX photography creating eerie, vast sky-scapes.", "plot": "The residents of a lonely gulch in inland California bear witness to an uncanny and chilling discovery.", "releaseDate": "2022-01-01" }
    ],
    "Greta Gerwig": [
        { "id": "lady-bird", "title": "Lady Bird", "year": 2017, "director": "Greta Gerwig", "writer": "Greta Gerwig", "cinematographer": "Sam Levy", "editor": "Nick Houy", "composer": "Jon Brion", "studio": "IAC Films / Scott Rudin Productions", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Lady+Bird", "focus": "Warm, nostalgic, lived-in Sacramento lighting, emphasizing deeply personal realism.", "plot": "In 2002, an artistically inclined seventeen-year-old girl comes of age in Sacramento, California.", "releaseDate": "2017-01-01" },
        { "id": "little-women", "title": "Little Women", "year": 2019, "director": "Greta Gerwig", "writer": "Greta Gerwig", "cinematographer": "Yorick Le Saux", "editor": "Nick Houy", "composer": "Alexandre Desplat", "studio": "Columbia Pictures / Regency Enterprises", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Little+Women", "focus": "Rich, golden hues for childhood memories contrasted with cooler tones for adult reality.", "plot": "Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.", "releaseDate": "2019-01-01" },
        { "id": "barbie", "title": "Barbie", "year": 2023, "director": "Greta Gerwig", "writer": "Greta Gerwig / Noah Baumbach", "cinematographer": "Rodrigo Prieto", "editor": "Nick Houy", "composer": "Mark Ronson / Andrew Wyatt", "studio": "Heyday Films / LuckyChap Entertainment / Mattel Films Production", "poster": "https://placehold.co/500x750/1a1a1a/e2b646?text=Barbie", "focus": "Vibrant, artificial, hyper-saturated practical sets bursting with unapologetic pinks.", "plot": "Barbie suffers a crisis that leads her to question her world and her existence.", "releaseDate": "2023-01-01" }
    ]
};

function fetchJson(url) {
    return new Promise(r => {
        const req = https.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, res => {
            let data = '';
            res.on('data', c => data += c);
            res.on('end', () => {
                try { r(JSON.parse(data)); } catch(e) { r(null); }
            });
        }).on('error', e => r(null));
        req.setTimeout(5000, () => { req.abort(); r(null); });
    });
}

function download(url, dest) {
    return new Promise((resolve, reject) => {
        const file = fs.createWriteStream(dest);
        const req = https.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, function(response) {
            response.pipe(file);
            file.on('finish', function() {
                file.close(resolve);
            });
        }).on('error', function(err) {
            fs.unlink(dest, () => {});
            reject(err);
        });
        req.setTimeout(5000, () => { req.abort(); reject(new Error('timeout')); });
    });
}

const wait = ms => new Promise(r => setTimeout(r, ms));

async function run() {
    const dataStr = fs.readFileSync('js/data.js', 'utf8');
    const match = dataStr.match(/const FILMS_DATA = (\{[\s\S]*?\});/);
    let data = eval('(' + match[1] + ')');
    let modified = false;

    for (let name in newData) {
        let dp = data.director.directors.find(p => p.name === name);
        
        if (dp) {
            dp.mustWatch = newData[name];
            console.log(`Replaced mustWatch for ${name}`);
            
            for (let m of dp.mustWatch) {
                let queryTitle = m.title.split('(')[0].replace(/[’']/g, '').trim();
                let query = encodeURIComponent(queryTitle);
                let url = `https://api.themoviedb.org/3/search/movie?api_key=${API_KEY}&query=${query}&year=${m.year}`;
                
                let retry = 3;
                let posterUrl = null;
                
                while(retry > 0 && !posterUrl) {
                    await wait(2000); // 2 second delay
                    console.log(`Searching TMDB for ${queryTitle}...`);
                    let mRes = await fetchJson(url);
                    
                    if (mRes && mRes.results && mRes.results.length > 0) {
                        let result = mRes.results.find(r => r.release_date && r.release_date.startsWith(m.year.toString()));
                        if (!result) result = mRes.results[0]; // fallback
                        
                        if (result && result.poster_path) {
                            posterUrl = 'https://image.tmdb.org/t/p/w500' + result.poster_path;
                        }
                    } else if (!mRes) {
                        console.log(`Failed fetch for ${queryTitle}, retrying...`);
                        retry--;
                        continue;
                    }
                    break;
                }

                if (posterUrl) {
                    console.log(`Found TMDB URL for ${m.title}`);
                    const filename = `assets/images/${queryTitle.toLowerCase().replace(/ /g, '_').replace(/[^a-z0-9_]/g, '')}.jpg`;
                    try {
                        await download(posterUrl, filename);
                        console.log(`Downloaded ${m.title}`);
                        m.poster = filename;
                    } catch (e) {
                        console.error(`Failed to download ${m.title}`);
                    }
                } else {
                    console.log(`Could not find poster for ${m.title} on TMDB`);
                }
            }
            modified = true;
        } else {
            console.log(`Could not find Director: ${name}`);
        }
    }

    if (modified) {
        let newContent = JSON.stringify(data, null, 4);
        const newFileContent = dataStr.substring(0, match.index) + 'const FILMS_DATA = ' + newContent + ';' + dataStr.substring(match.index + match[0].length);
        fs.writeFileSync('js/data.js', newFileContent, 'utf8');
        console.log("Successfully updated Hollywood & North American Masters 3");
    }
}

run();
